# Generated by Django 4.2.1 on 2023-07-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urlname", models.URLField()),
            ],
        ),
    ]
