# Generated by Django 4.2.1 on 2023-07-04 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web_api", "0002_weburl"),
    ]

    operations = [
        migrations.CreateModel(
            name="Urldetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("counts", models.IntegerField()),
                (
                    "userurl",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "weburls",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="web_api.weburl"
                    ),
                ),
            ],
        ),
    ]
