# Generated by Django 4.2.1 on 2023-07-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_api", "0003_urldetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="urldetail",
            name="updated",
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name="urldetail",
            name="counts",
            field=models.IntegerField(default=1),
        ),
    ]
